import os
import sys

import psycopg2 as dbapi2


INIT_STATEMENTS = [
    """CREATE TABLE IF NOT EXISTS USERS (
        ID SERIAL PRIMARY KEY,
        IS_ORGANIZATION BOOLEAN NOT NULL,
        IS_ADMIN BOOLEAN NOT NULL,
        USERNAME VARCHAR(50) UNIQUE NOT NULL,
        FIRSTNAME VARCHAR(50) NOT NULL,
        LASTNAME VARCHAR(50) NOT NULL,
        EMAIL VARCHAR(100) UNIQUE NOT NULL,
        PASSWORD VARCHAR(100) UNIQUE NOT NULL,
        DATE_CREATED DATE DEFAULT CURRENT_DATE,
        DATE_UPDATED DATE DEFAULT CURRENT_DATE
    ) 
    """,
    """CREATE TABLE IF NOT EXISTS SCHEDULES(
        ID SERIAL PRIMARY KEY,
        USER REFERENCES USERS(ID),
        EVENT REFERENCES EVENTS(ID),
        DATE_CREATED DATE DEFAULT CURRENT_DATE,
        DATE_UPDATED DATE DEFAULT CURRENT_DATE                
    )
    """,
    """CREATE TABLE IF NOT EXISTS EVENTS (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(200) NOT NULL,
        IS_PRIVATE BOOLEAN NOT NULL,
        PLACE REFERENCES ADDRESSES(ID),
        TYPE VARCHAR(50) NOT NULL,
        CREATOR REFERENCES USERS(ID),
        RATE NUMERIC(3,1),
        DATE DATE NOT NULL,
        DATE_CREATED DATE DEFAULT CURRENT_DATE,
        DATE_UPDATED DATE DEFAULT CURRENT_DATE
    ) 
    """,
    """CREATE TABLE IF NOT EXISTS EVENTATTENDSTATUSES (
        ID SERIAL PRIMARY KEY,
        USER REFERENCES USERS(ID),
        EVENT REFERENCES EVENTS(ID),
        STATUS BOOLEAN,
        DATE_CREATED DATE DEFAULT CURRENT_DATE,
        DATE_UPDATED DATE DEFAULT CURRENT_DATE
    )
    """,
    """CREATE TABLE IF NOT EXISTS ADDRESSES (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(100) NOT NULL,
        COUNTRY VARCHAR(100) NOT NULL,
        CITY VARCHAR(100) NOT NULL,
        LINE1 VARCHAR(200),
        LINE2 VARCHAR(200),
        DATE_CREATED DATE DEFAULT CURRENT_DATE,
        DATE_UPDATED DATE DEFAULT CURRENT_DATE        
    )
    """,
    """CREATE TABLE IF NOT EXISTS COMMENTS (
        ID SERIAL PRIMARY KEY,
        USER REFERENCES USERS(ID),
        EVENT REFERENCES EVENTS(ID),
        CONTEXT VARCHAR(500),
        DATE_CREATED DATE DEFAULT CURRENT_DATE,
        DATE_UPDATED DATE DEFAULT CURRENT_DATE
    )
    """,
    """CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(100),
        ADDRESS REFERENCES ADDRESSES(ID),
        EVENT REFERENCES EVENTS(ID),
        DATE_CREATED DATE DEFAULT CURRENT_DATE,
        DATE_UPDATED DATE DEFAULT CURRENT_DATE        
    )
    """
]


def initialize(url):
    with dbapi2.connect(url) as connection:
        cursor = connection.cursor()
        for statement in INIT_STATEMENTS:
            cursor.execute(statement)
        cursor.close()


if __name__ == "__main__":
    url = os.getenv("DATABASE_URL")
    if url is None:
        print("Usage: DATABASE_URL=url python dbinit.py", file=sys.stderr)
        sys.exit(1)
    initialize(url)
